-- MEDICINE_TYPE_MASTER
INSERT INTO MEDICINE_TYPE_MASTER(MEDICINE_TYPE_CODE, MEDICINE_TYPE_NAME) VALUES('T', 'Tablets');
INSERT INTO MEDICINE_TYPE_MASTER(MEDICINE_TYPE_CODE, MEDICINE_TYPE_NAME) VALUES('C', 'Capsules');
INSERT INTO MEDICINE_TYPE_MASTER(MEDICINE_TYPE_CODE, MEDICINE_TYPE_NAME) VALUES('S', 'Syrups');

-- MEDICINE_MASTER
INSERT INTO MEDICINE_MASTER(MEDICINE_CODE, MEDICINE_NAME) VALUES('MC-300', 'Panadol');
INSERT INTO MEDICINE_MASTER(MEDICINE_CODE, MEDICINE_NAME) VALUES('MC-301', 'Fepanil');
INSERT INTO MEDICINE_MASTER(MEDICINE_CODE, MEDICINE_NAME) VALUES('MC-302', 'Crocin');

-- SHIPPING_MASTER
INSERT INTO SHIPPING_MASTER(MEDICINE_TYPE_CODE, WEIGHT_RANGE, SHIPPING_CHARGE) VALUES('C', 'W1', 500);
INSERT INTO SHIPPING_MASTER(MEDICINE_TYPE_CODE, WEIGHT_RANGE, SHIPPING_CHARGE) VALUES('C', 'W2', 1000);
INSERT INTO SHIPPING_MASTER(MEDICINE_TYPE_CODE, WEIGHT_RANGE, SHIPPING_CHARGE) VALUES('C', 'W3', 1500);
INSERT INTO SHIPPING_MASTER(MEDICINE_TYPE_CODE, WEIGHT_RANGE, SHIPPING_CHARGE) VALUES('T', 'W1', 200);
INSERT INTO SHIPPING_MASTER(MEDICINE_TYPE_CODE, WEIGHT_RANGE, SHIPPING_CHARGE) VALUES('T', 'W2', 500);
INSERT INTO SHIPPING_MASTER(MEDICINE_TYPE_CODE, WEIGHT_RANGE, SHIPPING_CHARGE) VALUES('T', 'W3', 1000);
INSERT INTO SHIPPING_MASTER(MEDICINE_TYPE_CODE, WEIGHT_RANGE, SHIPPING_CHARGE) VALUES('S', 'W1', 1000);
INSERT INTO SHIPPING_MASTER(MEDICINE_TYPE_CODE, WEIGHT_RANGE, SHIPPING_CHARGE) VALUES('S', 'W2', 1500);
INSERT INTO SHIPPING_MASTER(MEDICINE_TYPE_CODE, WEIGHT_RANGE, SHIPPING_CHARGE) VALUES('S', 'W3', 2000);