-- MEDICINE_TYPE_MASTER
CREATE TABLE IF NOT EXISTS MEDICINE_TYPE_MASTER (
    MEDICINE_TYPE_CODE CHAR(2) PRIMARY KEY,
    MEDICINE_TYPE_NAME VARCHAR(20)
);

-- MEDICINE_MASTER
CREATE TABLE IF NOT EXISTS MEDICINE_MASTER (
    MEDICINE_CODE VARCHAR(8) PRIMARY KEY,
    MEDICINE_NAME VARCHAR(30)
);

-- SHIPPING_MASTER
CREATE TABLE IF NOT EXISTS SHIPPING_MASTER (
    MEDICINE_TYPE_CODE CHAR(2),
    WEIGHT_RANGE VARCHAR(2),
    SHIPPING_CHARGE DECIMAL(7,2),
    PRIMARY KEY (MEDICINE_TYPE_CODE, WEIGHT_RANGE)
);

-- BATCH_INFO
CREATE TABLE IF NOT EXISTS BATCH_INFO (
    BATCH_CODE VARCHAR(8) PRIMARY KEY,
    MEDICINE_CODE VARCHAR(8),
    WEIGHT INT,
    PRICE DECIMAL(7,2),
    MEDICINE_TYPE_CODE CHAR(2),
    SHIPPING_CHARGE DECIMAL(7,2),
    CARE_LEVEL VARCHAR(15),
    REFRIGERATION_REQUIRED BOOLEAN,
    FOREIGN KEY (MEDICINE_CODE) REFERENCES MEDICINE_MASTER(MEDICINE_CODE),
    FOREIGN KEY (MEDICINE_TYPE_CODE) REFERENCES MEDICINE_TYPE_MASTER(MEDICINE_TYPE_CODE)
);